#ifndef WEB_PAGES_H
#define WEB_PAGES_H

#include <Arduino.h>
#include "Globals.h"
#include "ConfigManager.h"
#include "StorageService.h"

inline String htmlDashboard() {
  String h;
  h += F("<!doctype html><html><head><meta charset='UTF-8'><meta name=viewport content='width=device-width,initial-scale=1'>");
  h += F("<title>Command Center - Blood Bank Monitor</title><style>"
  "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap');"
  ":root{--bg:#f8fafc;--card:#ffffff;--border:#e2e8f0;--accent:#2563eb;--text:#0f172a;--sub:#64748b;--ok:#10b981;--bad:#ef4444}"
  "body{margin:0;background:var(--bg);color:var(--text);font:16px 'Inter',system-ui,-apple-system;overflow-x:hidden}"
  ".wrap{max-width:900px;margin:auto;padding:24px}"
  "header{display:flex;justify-content:space-between;align-items:center;margin-bottom:32px}"
  "h1{font-size:24px;font-weight:800;letter-spacing:-1px;margin:0;background:linear-gradient(90deg,var(--text),var(--sub));-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}"
  ".card{background:var(--card);border:1px solid var(--border);border-radius:24px;padding:32px;box-shadow:0 20px 40px rgba(0,0,0,0.05);position:relative;overflow:hidden}"
  ".card::after{content:'';position:absolute;top:0;right:0;width:150px;height:150px;background:var(--accent);filter:blur(100px);opacity:0.1;pointer-events:none}"
  ".big-t{font-size:96px;font-weight:900;text-align:center;margin:20px 0;letter-spacing:-4px;line-height:1;position:relative}"
  ".big-t span{font-size:32px;font-weight:500;color:var(--sub);vertical-align:top;margin-left:4px}"
  ".status-chip{padding:8px 16px;border-radius:999px;font-size:13px;font-weight:700;letter-spacing:1px;text-transform:uppercase;border:1px solid transparent}"
  ".status-ok{background:rgba(16,185,129,0.1);color:var(--ok);border-color:rgba(16,185,129,0.2)}"
  ".status-bad{background:rgba(239,68,68,0.1);color:var(--bad);border-color:rgba(239,68,68,0.2);animation:pulse 2s infinite}"
  "@keyframes pulse{0%{opacity:1}50%{opacity:0.6}100%{opacity:1}}"
  ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:24px;margin-top:32px}"
  ".sub-card{background:rgba(0,0,0,0.02);border:1px solid var(--border);padding:16px;border-radius:18px}"
  ".label{color:var(--sub);font-size:12px;text-transform:uppercase;font-weight:600;margin-bottom:6px;letter-spacing:0.5px}"
  ".val{font-size:18px;font-weight:600}"
  ".nav-bar{display:flex;gap:12px;margin-top:24px;border-top:1px solid var(--border);padding-top:24px}"
  ".btn{background:rgba(0,0,0,0.05);border:1px solid var(--border);padding:12px 20px;border-radius:14px;color:var(--text);font-size:14px;font-weight:600;text-decoration:none;transition:0.2s;cursor:pointer;flex:1;text-align:center}"
  ".btn:hover{background:var(--accent);color:white;border-color:var(--accent)}"
  ".btn-red:hover{background:var(--bad);border-color:var(--bad)}"
  ".chart-con{margin-top:24px;background:var(--card);border:1px solid var(--border);border-radius:24px;padding:20px;height:220px}"
  ".toast{position:fixed;left:50%;bottom:32px;transform:translateX(-50%) translateY(20px);background:var(--accent);color:white;border:1px solid var(--border);padding:12px 24px;border-radius:16px;opacity:0;transition:0.3s;font-size:14px;font-weight:600;pointer-events:none;z-index:1000}"
  ".toast.show{opacity:1;transform:translateX(-50%) translateY(0)}"
  "</style></head><body>");

  h += F("<div class='wrap'>"
  "<header><h1>Blood Bank <span style='font-weight:300'>Live</span></h1><div id='st' class='status-chip'>—</div></header>"
  "<div class='card' style='margin-bottom:24px; text-align:center; padding:24px;'>"
  "<div class='label'>Current Time</div>"
  "<div id='live-clock' style='font-size:28px; font-weight:800; margin-top:8px;'>--/--/----, --:--:-- --</div>"
  "</div>"
  "<div class='card'>"
  "<div class='label' style='text-align:center'>Current Temperature</div>"
  "<div class='big-t' id='t'>--.-<span>&deg;C</span></div>"
  "<div class='grid'>"
  "<div class='sub-card'><div class='label'>Safe Range</div><div class='val' id='rng'>-- &ndash; -- &deg;C</div></div>"
  "<div class='sub-card'><div class='label'>Min / Max (24h)</div><div class='val' id='mm'>-- / -- &deg;C</div></div>"
  "<div class='sub-card'><div class='label'>Last Report</div><div class='val' id='ts'>Just now</div></div>"
  "</div>"
  "</div>"

  "<div class='grid'>"
  "<div class='sub-card'>"
  "<div class='label'>Alert Control</div>"
  "<div style='display:flex;gap:8px;margin-top:8px'>"
  "<button id='on' class='btn btn-red'>Mute Off</button>"
  "<button id='off' class='btn'>Mute Buzzer</button>"
  "</div>"
  "</div>"
  "<div class='sub-card'><div class='label'>Cloud Sync</div><div class='val' id='cloud-st'>Inactive</div></div>"
  "<div class='sub-card'><div class='label'>GSM Link</div><div class='val' id='gsm-st'>Standby</div></div>"
  "</div>"

  "<div class='card' style='margin-top:24px; padding:24px;'>"
  "<div class='label' style='display:flex; justify-content:space-between;'>"
  "<span>Daily Temperature Snapshots</span>"
  "<span style='opacity: 0.5;'>Plan B</span>"
  "</div>"
  "<style>"
  ".snap-table{width:100%; border-collapse:collapse; margin-top:16px;}"
  ".snap-table th, .snap-table td{padding:12px; text-align:center; border-bottom:1px solid var(--border);}"
  ".snap-table th{font-size:10px; text-transform:uppercase; color:var(--sub);}"
  ".snap-table td{font-size:16px; font-weight:700;}"
  ".snap-time{font-size:10px; font-weight:400; color:var(--sub); display:block;}"
  "</style>"
  "<table class='snap-table'>"
  "<thead><tr>"
  "<th>Morning<span class='snap-time'>06:00</span></th>"
  "<th>Afternoon<span class='snap-time'>12:00</span></th>"
  "<th>Evening<span class='snap-time'>18:00</span></th>"
  "<th>Night<span class='snap-time'>00:00</span></th>"
  "</tr></thead>"
  "<tbody><tr>"
  "<td id='snap-morning'>--.-°C</td>"
  "<td id='snap-afternoon'>--.-°C</td>"
  "<td id='snap-evening'>--.-°C</td>"
  "<td id='snap-night'>--.-°C</td>"
  "</tr></tbody>"
  "</table>"
  "</div>"

  "<div class='chart-con'><canvas id='bars'></canvas></div>"
  "<div class='nav-bar'>"
  "<a href='/settings' class='btn'>System Settings</a>"
  "<a href='/history' class='btn'>View History</a>"
  "</div>"

  "<footer style=\"margin-top: 60px; padding: 40px 0; border-top: 1px solid var(--border); text-align: center; color: var(--sub); font-size: 13px; line-height: 1.6;\">"
  "<p style=\"font-weight: 800; color: var(--text); letter-spacing: 0.5px; margin-bottom: 20px;\">SESSION : 2025/2026 - M.23/HND/I&C</p>"
  "<div style=\"margin-bottom: 20px;\">"
  "<p style=\"font-weight: 700; color: var(--text); margin: 0;\">ENGR. Dr. ABDULAZEEZ D. EL-LADAN</p>"
  "<p style=\"margin: 0;\">Project Supervisor</p>"
  "</div>"
  "<div style=\"margin-bottom: 20px;\">"
  "<p style=\"font-weight: 700; color: var(--text); margin: 0;\">ENGR. (Dr.) ABDULHAMID MUSA</p>"
  "<p style=\"margin: 0;\">Head of Department</p>"
  "</div>"
  "<div style=\"margin-top: 24px; padding-top: 20px; border-top: 1px dashed var(--border);\">"
  "<p style=\"font-weight: 700; color: var(--text); margin: 0;\">OKAFOR CHINASOM MATTHEW, OGHARSI DAVID</p>"
  "<p style=\"margin: 0;\">Project students</p>"
  "</div>"
  "</footer>"

  "<div id='toast' class='toast'></div>"
  "</div>");

  h += F("<script>"
"const $=s=>document.querySelector(s);"
"let isCloud = window.location.hostname !== '192.168.4.1' && window.location.hostname !== 'localhost';"
"let isEditing = false;"
"const fbUrl = 'https://bloodbankmonitor-35b6f-default-rtdb.firebaseio.com';"
"const updateClock=()=>{const now=new Date();const options={year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hour12:true};$('#live-clock').textContent=now.toLocaleString('en-US',options);};"
"const updateSnaps=(a)=>{const targets=[6,12,18,0],res={};a.forEach(p=>{let h=-1;if(typeof p.ts==='string'){const m=p.ts.match(/(\\d{1,2}):(\\d{2}):/);if(m)h=parseInt(m[1]);}else if(typeof p.ts==='number'){h=new Date(p.ts*1000).getHours();}if(h>=0){targets.forEach(t=>{if(Math.abs(h-t)<2)res[t]=p.t.toFixed(1)+'°C';});}});if(res[6])$('#snap-morning').textContent=res[6];if(res[12])$('#snap-afternoon').textContent=res[12];if(res[18])$('#snap-evening').textContent=res[18];if(res[0])$('#snap-night').textContent=res[0];};"
"if(isCloud) document.addEventListener('DOMContentLoaded', ()=> { "
" $('h1').innerHTML += ' <small style=\"color:#3b82f6;font-size:12px\">(Remote)</small>'; "
" document.querySelectorAll('input').forEach(i => { "
"  i.onfocus = () => { isEditing = true; }; "
"  i.onblur = () => { setTimeout(()=>isEditing=false, 2000); }; "
" });"
"});"
"updateClock();setInterval(updateClock,1000);"
"async function pull(){"
" if(isEditing) return;"
" try{"
"  let j;"
"  if(isCloud && fbUrl){"
"   const r=await fetch(fbUrl + '/device.json'); j=await r.json();"
"   if(!j) throw 'Cloud empty';"
"   const rh=await fetch(fbUrl + '/history.json?limitToLast=1000');"
"   const jh=await rh.json(); if(jh) { const pts=Object.keys(jh).map(k=>({ts:parseInt(jh[k].ts||k),t:jh[k].t})); drawChartFromFirebase(jh); updateSnaps(pts); }"
"  } else {"
"   const r=await fetch('/api/info'); j=await r.json();"
"  }"
"  $('#t').innerHTML=(isFinite(j.temp)?j.temp.toFixed(1):'--')+'<span>&deg;C</span>';"
"  $('#rng').innerHTML=`${j.low.toFixed(1)} - ${j.high.toFixed(1)}&deg;C`;"
"  if(isCloud && j.low===undefined) $('#rng').innerHTML='--';"
"  $('#mm').innerHTML=`${j.min.toFixed(1)} / ${j.max.toFixed(1)}&deg;C`;"
"  const cld=$('#cloud-st');"
"  if(isCloud && j.lastUpdate) {"
"    const ago = Math.floor((Date.now()/1000 - j.lastUpdate));"
"    if(ago < 60) { "
"      cld.textContent = 'Active (Live)'; cld.style.color='var(--ok)';"
"    } else {"
"      const m = Math.floor(ago/60);"
"      cld.textContent = 'Offline (' + (m>0?m+'m':'<1m') + ' ago)'; cld.style.color='var(--bad)';"
"    }"
"  } else if(!isCloud) {"
"    cld.textContent = j.fbu ? 'Configured' : 'No URL'; cld.style.color='inherit';"
"  }"
"  $('#gsm-st').textContent = j.lastSms ? 'Sent ' + j.lastSms : 'Standby';"
"  let tsVal = j.time;"
"  if(isCloud && j.lastUpdate) {"
"    const ago = Math.floor((Date.now()/1000 - j.lastUpdate));"
"    tsVal = (ago < 60) ? ago + 's ago' : Math.floor(ago/60) + 'm ago';"
"  }"
"  $('#ts').textContent=tsVal||'—';"
"  const st=$('#st');"
"  if(j.alarm){"
"    st.textContent='ALARM ACTIVATED';st.className='status-chip status-bad';"
"    $('#t').style.color='var(--bad)';"
"  }else{"
"    st.textContent='SYSTEM SECURE';st.className='status-chip status-ok';"
"    $('#t').style.color='inherit';"
"  }"
" } catch(e){ console.error(e); }"
"}"
"function renderChart(sub){"
" const c=$('#bars'),x=c.getContext('2d');"
" const DPR=window.devicePixelRatio||1;"
" const W=c.clientWidth,H=c.clientHeight;"
" c.width=W*DPR;c.height=H*DPR;x.scale(DPR,DPR);x.clearRect(0,0,W,H);"
" if(!sub || sub.length<2){x.fillStyle='#94a3b8';x.fillText('Waiting for data...',10,20);return;}"
" const L=60,R=20,T=16,B=40,w=W-L-R,h=H-T-B;"
" const vals=sub.map(o=>o.t);"
" let lo=Math.min(...vals,1.0)-1, hi=Math.max(...vals,7.0)+1;"
" const X=i=>L+i*(w/(sub.length-1)), Y=v=>T+(1-(v-lo)/(hi-lo))*h;"
 " x.strokeStyle='rgba(0,0,0,.05)';x.beginPath();"
" for(let i=0;i<=5;i++){const gy=T+i*h/5;x.moveTo(L,gy);x.lineTo(W-R,gy);}x.stroke();"
 " x.fillStyle='rgba(37,99,235,.05)';x.fillRect(L,Y(6),w,Y(2)-Y(6));"
 " x.strokeStyle='rgba(239,68,68,.3)';x.beginPath();x.moveTo(L,Y(2));x.lineTo(W-R,Y(2));x.moveTo(L,Y(6));x.lineTo(W-R,Y(6));x.stroke();"
 " x.strokeStyle='#2563eb';x.lineWidth=2.5;x.beginPath();x.moveTo(X(0),Y(sub[0].t));"
" for(let i=1;i<sub.length;i++){x.lineTo(X(i),Y(sub[i].t));}x.stroke();"
 " x.fillStyle='#64748b';x.font='10px Inter';"
" for(let i=0;i<=4;i++){const val=lo+i*(hi-lo)/4;x.fillText(val.toFixed(1),10,Y(val)+4);}"
"}"
"function drawChartFromFirebase(jh){"
" const pts = Object.keys(jh).map(k => ({ ts: k, t: jh[k].t }));"
" renderChart(pts.slice(-24));"
"}"
"async function bars(){"
" if(isCloud) return;"
" try{const res=await fetch('/api/recent_log');if(!res.ok)return;const txt=await res.text();"
" const rows=txt.trim().split(/\\n/);if(rows.length<2)return;"
" const a=[];for(let i=1;i<rows.length;i++){const [ts,tc]=rows[i].split(',');if(!ts)continue;a.push({ts:ts,t:parseFloat(tc)});} "
" renderChart(a.slice(-24)); updateSnaps(a);"
" }catch(e){}"
"}"
"pull();bars();setInterval(pull,5000);"
"</script></body></html>");
  return h;
}

inline String htmlSettings(){
  String h;
  h += F("<!doctype html><html><head><meta charset='UTF-8'><meta name=viewport content='width=device-width,initial-scale=1'>"
  "<title>Settings - Blood Bank Monitor</title><style>"
  ":root{--bg:#f8fafc;--card:#ffffff;--border:#e2e8f0;--accent:#2563eb;--text:#0f172a;--sub:#64748b}"
  "body{margin:0;background:var(--bg);color:var(--text);font:16px 'Inter',system-ui,-apple-system;overflow-x:hidden}"
  ".wrap{max-width:700px;margin:24px auto;padding:0 20px}"
  "h2{font-size:24px;margin-bottom:24px;font-weight:700;letter-spacing:-0.5px}"
  "h3{font-size:16px;margin:0 0 16px;color:var(--sub);text-transform:uppercase;letter-spacing:1px;font-weight:600}"
  ".card{background:var(--card);border:1px solid var(--border);border-radius:20px;padding:24px;margin-bottom:24px;box-shadow:0 12px 30px rgba(0,0,0,0.05);position:relative;overflow:hidden}"
  ".card::before{content:'';position:absolute;top:0;left:0;right:0;height:4px;background:linear-gradient(90deg,transparent,var(--accent),transparent);opacity:0.3}"
  "label{display:block;margin-bottom:8px;color:var(--sub);font-size:13px;font-weight:500}"
  "input,button,select{font-size:15px;padding:12px 16px;border-radius:12px;border:1px solid var(--border);background:#ffffff;color:var(--text);width:100%;box-sizing:border-box;transition:all 0.2s}"
  "input:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px rgba(37,99,235,0.1)}"
  ".row{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px}"
  "@media(max-width:500px){.row{grid-template-columns:1fr}}"
  ".btn-nav{display:inline-flex;align-items:center;padding:10px 18px;border-radius:14px;background:rgba(0,0,0,0.05);color:var(--text);text-decoration:none;font-size:14px;font-weight:500;margin-right:10px;border:1px solid var(--border);transition:0.2s}"
  ".btn-nav:hover{background:rgba(0,0,0,0.1);border-color:var(--sub)}"
  ".btn-primary{background:var(--accent);color:white;border:none;font-weight:600;cursor:pointer;margin-top:10px}"
  ".btn-primary:hover{opacity:0.9;transform:translateY(-1px)}"
  ".btn-danger{background:#7f1d1d;color:#ffffff;border-color:#991b1b;cursor:pointer}"
  ".btn-danger:hover{background:#991b1b}"
  ".cb-row{display:flex;align-items:center;gap:12px;margin:12px 0;cursor:pointer}"
  ".cb-row input{width:auto;margin:0}"
  ".toast{position:fixed;left:50%;bottom:32px;transform:translateX(-50%) translateY(20px);background:var(--accent);color:white;border:1px solid var(--border);padding:12px 24px;border-radius:16px;opacity:0;transition:0.3s;font-size:14px;font-weight:600;pointer-events:none;z-index:1000}"
  ".toast.show{opacity:1;transform:translateX(-50%) translateY(0)}"
  "</style></head><body>");

  h += F("<div class='wrap'>"
  "<div style='margin-bottom:32px'><a class='btn-nav' href='/'>Dashboard</a> <a class='btn-nav' href='/history'>History</a></div>"
  "<h2>System Configuration</h2>"

  "<div class='card'><h3>Network (Internet)</h3>"
  "<label>Wi-Fi Name (SSID)</label><input id='wss' placeholder='Hotspot or Router Name'>"
  "<label style='margin-top:16px'>Wi-Fi Password</label><input id='wqs' type='password' placeholder='Enter password'>"
  "<small style='display:block;margin-top:12px;color:#64748b;font-size:11px'>Cloud is automatically configured to <b>bloodbankmonitor-35b6f</b></small>"
  "</div>"

  "<div class='card'><h3>Monitoring Setpoints</h3>"
  "<div class='row'>"
  "<div><label>Low Limit (&deg;C)</label><input id='low' type='number' step='0.1'></div>"
  "<div><label>High Limit (&deg;C)</label><input id='high' type='number' step='0.1'></div>"
  "</div>"
  "</div>"

  "<div class='card'><h3>Notifications</h3>"
  "<label>Phone Numbers (comma separated)</label><input id='phones' placeholder='+234...'>"
  "<div class='row' style='margin-top:16px'>"
  "<div><label>SMS Interval (min)</label><input id='smsmin' type='number' min='1'></div>"
  "</div>"
  "<label class='cb-row'><input id='devsnd' type='checkbox'> Device Sound (Buzzer)</label>"
  "<label class='cb-row'><input id='call' type='checkbox'> Enable Calls on Alarm</label>"
  "<div style='margin-top:16px'><button id='save' class='btn-primary'>Apply & Save Changes</button></div>"
  "</div>"

  "<div class='card'><h3>System Maintenance</h3>"
  "<div class='row'>"
  "<button id='resetmm'>Reset Min/Max</button>"
  "<button id='test'>Test SMS</button>"
  "</div>"
  "<div class='row' style='margin-top:12px'>"
  "<button id='clearlog'>Clear Data Log</button>"
  "<button id='factory' class='btn-danger'>Factory Reset</button>"
  "</div>"
  "</div>");

  h += F("<div id='toast' class='toast'>Saved</div></div>"
  "<script>"
  "const $=s=>document.querySelector(s);"
"function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000);}"
"async function seed(){"
" const b=await fetch('/api/getcfg');const c=await b.json();"
" $('#low').value=c.low;$('#high').value=c.high;"
" $('#wss').value=c.wss||'';$('#wqs').value=c.wqs||'';"
" $('#phones').value=c.phones||'';$('#devsnd').checked=c.sound;$('#call').checked=c.call;$('#smsmin').value=c.smsmin||5;"
"}"
"$('#save').onclick=async()=>{ "
" if(window.location.hostname !== '192.168.4.1' && window.location.hostname !== 'localhost') {"
"   const fbUrl = 'https://bloodbankmonitor-35b6f-default-rtdb.firebaseio.com';"
"   const data = { "
"     low: parseFloat($('#low').value), "
"     high: parseFloat($('#high').value), "
"     sound: $('#devsnd').checked ? 1 : 0, "
"     phones: $('#phones').value, "
"     smsmin: parseInt($('#smsmin').value), "
"     call: $('#call').checked ? 1 : 0 "
"   };"
"   const r = await fetch(fbUrl + '/settings.json', { method:'PATCH', body: JSON.stringify(data) });"
"   if(r.ok) { toast('Cloud Settings Applied'); isEditing=false; } "
"   return;"
" }"
" const fd=new FormData();"
" fd.append('low',$('#low').value);fd.append('high',$('#high').value);"
" fd.append('phones',$('#phones').value);fd.append('smsmin',$('#smsmin').value);"
" fd.append('wss',$('#wss').value);fd.append('wqs',$('#wqs').value);"
" if($('#devsnd').checked)fd.append('sound','1');if($('#call').checked)fd.append('call','1');"
" const r = await fetch('/api/savecfg',{method:'POST',body:fd});"
" if(r.ok) { toast('Local Configuration Saved'); } else { toast('Error saving'); }"
"};"
  "$('#test').onclick=async()=>{const r=await fetch('/api/testsms');if(r.ok)toast('Test SMS sent');};"
  "$('#resetmm').onclick=async()=>{if(!confirm('Reset Min/Max to current temperature?'))return;await fetch('/api/resetminmax');toast('Min/Max reset');};"
  "$('#clearlog').onclick=async()=>{if(!confirm('Clear all logged data (CSV)?'))return;await fetch('/api/clearlog');toast('Log cleared');};"
  "$('#factory').onclick=async()=>{if(!confirm('Factory reset and reboot now?'))return;await fetch('/api/factoryreset');toast('Rebooting\u2026');};"
  "seed();"
  "</script></body></html>");

  return h;
}

inline String htmlHistory(){
  String h;
  h += F("<!doctype html><html><head><meta charset='UTF-8'><meta name=viewport content='width=device-width,initial-scale=1'>"
         "<title>History</title><style>"
         "body{margin:0;background:#f8fafc;color:#0f172a;font:16px 'Inter',ui-sans-serif}"
         ".wrap{max-width:1024px;margin:18px auto;padding:0 16px}"
         ".card{background:#ffffff;border:1px solid #e2e8f0;border-radius:14px;padding:16px;box-shadow:0 4px 12px rgba(0,0,0,0.05)}"
         "canvas{width:100%;height:380px;border-radius:12px}"
         "a.btn{display:inline-block;padding:10px 14px;border-radius:12px;border:1px solid #e2e8f0;color:#64748b;text-decoration:none;margin:12px 0;background:#ffffff;font-weight:600}"
         "a.btn:hover{background:#f1f5f9;color:#0f172a}"
         "</style></head><body>");
  h += F("<div class='wrap'><a class='btn' href='/'>Dashboard</a> <a class='btn' href='/settings'>Settings</a> <a class='btn' href='/log.csv'>Download CSV</a>"
         "<div class='card'><h3 style='margin:0 0 10px'>Temperature Over Time</h3><canvas id='c'></canvas>"
         "<small>Timestamp from GSM clock when available, else device uptime.</small></div></div>");
  h += F("<script>"
"async function load(){const r=await fetch('/log.csv');if(!r.ok)return null;const t=await r.text();const L=t.trim().split(/\\r?\\n/);if(L.length<2)return null;const a=[];for(let i=1;i<L.length;i++){const [ts,tc,al]=L[i].split(',');if(!ts)continue;a.push({ts:ts,t:+tc,a:+al});}return a;}"
"function draw(d){const c=document.getElementById('c');const x=c.getContext('2d');const W=c.clientWidth,H=c.clientHeight;c.width=W*devicePixelRatio;c.height=H*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);x.clearRect(0,0,W,H);if(!d||d.length<2){x.fillStyle='#64748b';x.fillText('No data yet',10,20);return;}const L=70,R=20,T=16,B=50;const w=W-L-R,h=H-T-B;const vals=d.map(v=>v.t);let lo=Math.min(...vals,1.0),hi=Math.max(...vals,7.0);const X=i=>L+i*(w/(d.length-1)),Y=v=>T+(1-(v-lo)/(hi-lo))*h;x.strokeStyle='rgba(0,0,0,.05)';x.beginPath();for(let i=0;i<=5;i++){const gy=T+i*h/5;x.moveTo(L,gy);x.lineTo(W-R,gy);}x.stroke();x.fillStyle='rgba(37,99,235,.05)';const y6=Y(6),y2=Y(2);x.fillRect(L,Math.min(y6,y2),w,Math.abs(y2-y6));x.strokeStyle='rgba(239,68,68,.3)';x.beginPath();x.moveTo(L,Y(2));x.lineTo(W-R,Y(2));x.moveTo(L,Y(6));x.lineTo(W-R,Y(6));x.stroke();x.strokeStyle='#2563eb';x.lineWidth=2.5;x.beginPath();x.moveTo(X(0),Y(d[0].t));for(let i=1;i<d.length;i++){x.lineTo(X(i),Y(d[i].t));}x.stroke();x.fillStyle='#64748b';x.font='12px Inter';const tickN=Math.min(8,d.length);for(let i=0;i<tickN;i++){const idx=Math.floor(i*(d.length-1)/(tickN-1));const px=X(idx);x.fillText(d[idx].ts, px-30, H-10);}for(let i=0;i<=4;i++){const val=lo+i*(hi-lo)/4;const py=Y(val);x.fillText(val.toFixed(1)+'&deg;C',6,py-4);} }"
"(async()=>{const d=await load();draw(d);})();"
"</script></body></html>");
  return h;
}

#endif
